### ISSUE TITLE
Question not an issue

### ISSUE THREAD

**Issue by Mut1nyJD** [Hobbes74/Terra-Invicta-XCOM-1983#1]
Wow this is quiet a comprehensible MOD congrats. 

I've thought of building my own MOD project on this one as this seems to be a very good starting point however I've got a specific idea and I wonder if  by chance you know if that's possible or not.

Basically what I want to do is change the arrival of the alien in the solar system and put it into the future so you start the game without the aliens already being around. From your MOD I noticed you can change the game start date. 
The ideas is I want the player to have maybe a couple of decades before the alien invasion fleet arrives and also wind the tech tree back in time basically to 1960s around the time the SETI project started on Earth

**Comment by Hobbes74** [comment]
HI there

There's already an official 2030 scenario in development (you can check it on the template files) that starts the alien invasion later. That's likely what you're looking after.

**Comment by Mut1nyJD** [comment]
Thanks for the tip I forgot about that I will do! Thank you
